#!/usr/bin/env python3
"""Bundle multi-module example algorithms into one self-contained script_text.

The eval harness only stores/runs a single ``script_text`` file. Sibling
modules under ``examples/`` are *not* put on PYTHONPATH (outside imports are
blocked). Use this bundler so seed baselines and multi-file algorithms become
one file that still re-exports ``predict``.

stdlib and installed third-party packages are left to normal import — only
repo-local source modules need inlining.
"""
from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent


def _read(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"missing module source: {path}")
    return path.read_text(encoding="utf-8")


def bundle_modules(
    modules: Sequence[Tuple[str, str]],
    *,
    entry: str,
    banner: Iterable[str] | None = None,
) -> str:
    """Return a self-contained Python source string.

    ``modules`` is an ordered list of ``(import_name, source_text)``. Earlier
    modules are installed first so later ones can ``import`` them. ``entry`` is
    the module name that must define ``predict``.
    """
    names = [n for n, _ in modules]
    if entry not in names:
        raise ValueError(f"entry module {entry!r} not in modules {names}")

    lines: List[str] = [
        "# Self-contained submission bundle.",
        "# Generated by tools/bundle_submission.py — edit sources under examples/.",
        "# Runtime may use the Python stdlib and installed site-packages only;",
        "# repo-local / sibling modules must be inlined here (not imported from disk).",
        "",
    ]
    if banner:
        for line in banner:
            lines.append("# " + line if line else "#")
        lines.append("")

    lines.extend(
        [
            "from __future__ import annotations",
            "",
            "import base64",
            "import sys",
            "import types",
            "",
            "def __poi_install_inline__(name: str, b64: str) -> None:",
            '    """Install one inlined module into sys.modules before entry runs."""',
            "    src = base64.b64decode(b64.encode('ascii')).decode('utf-8')",
            "    mod = types.ModuleType(name)",
            "    mod.__file__ = f'<submission-bundle>/{name}.py'",
            "    mod.__package__ = None",
            "    sys.modules[name] = mod",
            "    exec(compile(src, mod.__file__, 'exec'), mod.__dict__)",
            "",
        ]
    )

    for name, source in modules:
        b64 = base64.b64encode(source.encode("utf-8")).decode("ascii")
        lines.append(f"__poi_install_inline__({name!r}, (")
        chunk = 76
        for i in range(0, len(b64), chunk):
            lines.append(f"    {b64[i:i + chunk]!r}")
        lines.append("))")
        lines.append("")

    lines.extend(
        [
            f"_entry = sys.modules[{entry!r}]",
            "predict = _entry.predict",
            "if hasattr(_entry, 'DESCRIPTION'):",
            "    DESCRIPTION = _entry.DESCRIPTION",
            "if hasattr(_entry, 'RULE_VERSION'):",
            "    RULE_VERSION = _entry.RULE_VERSION",
            "if hasattr(_entry, 'decide'):",
            "    decide = _entry.decide",
            "",
        ]
    )
    return "\n".join(lines)


def bundle_paths(
    module_paths: Sequence[Tuple[str, Path]],
    *,
    entry: str,
    banner: Iterable[str] | None = None,
) -> str:
    modules = [(name, _read(path)) for name, path in module_paths]
    return bundle_modules(modules, entry=entry, banner=banner)


def bundle_example_ensemble_v2() -> str:
    ex = _ROOT / "examples"
    return bundle_paths(
        [
            ("mapkit_weighted", ex / "mapkit_weighted.py"),
            ("selector_list_fit", ex / "selector_list_fit.py"),
            ("selector_access_ocr", ex / "selector_access_ocr.py"),
            ("mapkit_vlm_live", ex / "mapkit_vlm_live.py"),
            ("mapkit_baseline_v2", ex / "mapkit_baseline_v2.py"),
        ],
        entry="mapkit_baseline_v2",
        banner=[
            "mapkit-baseline v2 — fully live ensemble (no curated residual list).",
            "list_fit@K20; on access≈nearest: live FastVLM skill@K5 (high-conf only).",
            "Default POI_VLM_MODE=live REQUIRES FastVLM (venv+MPS+checkpoint); missing env aborts the run.",
            "POI_VLM_MODE=off → deterministic core only (honest; not an ensemble score).",
            "Interpreter: POI_PREDICT_PYTHON or poi-data/tools/fastvlm-venv.",
        ],
    )


def bundle_example_ocr_override() -> str:
    ex = _ROOT / "examples"
    return bundle_paths(
        [
            ("mapkit_weighted", ex / "mapkit_weighted.py"),
            ("poi_confidence_policy", ex / "poi_confidence_policy.py"),
            ("mapkit_ocr_override", ex / "mapkit_ocr_override.py"),
        ],
        entry="mapkit_ocr_override",
        banner=[
            "mapkit-baseline v1 — Bloggo weighted + unique OCR name override.",
            "Self-contained bundle of mapkit_weighted + poi_confidence_policy + entry.",
        ],
    )


def detect_refresh_preset(run_name: str, script_text: str) -> Optional[str]:
    """Which current-repo source to use when Re-run loads a prior run.

    Returns:
      ``"ensemble_v2"`` | ``"ocr_override"`` | ``"nearest"`` | ``None``
      (None = keep stored script_text as-is).
    """
    name = (run_name or "").strip().lower()
    script = script_text or ""
    low = script.lower()

    if name in ("baseline-nearest", "nearest") or name.startswith("baseline-nearest"):
        return "nearest"

    # Explicit multi-module / VLM ensemble markers (incl. base64-wrapped source).
    ensemble_markers = (
        "mapkit_vlm_live",
        "selector_list_fit",
        "selector_access_ocr",
        "mapkit_baseline_v2",
        "_ensure_vlm_environment",
        "vlm_unavailable",  # old soft + new fail-loud both mention this
        "ensemble_v2",
        "list_fit",
    )
    ocr_v1_markers = (
        "mapkit_ocr_override",
        "ocr_name_support",
        "unique-direct-ocr-name-support",
        "poi_confidence_policy",
        "unique_ocr_name_override",
    )

    if name in ("mapkit-baseline", "mapkit_baseline") or name.startswith("mapkit-baseline"):
        if any(m in script or m in low for m in ensemble_markers):
            return "ensemble_v2"
        if any(m in script or m in low for m in ocr_v1_markers):
            return "ocr_override"
        # Name is mapkit-baseline but script is ambiguous — prefer current v2
        # policy when the stored body looks like a multi-file seed entrypoint.
        if "mapkit_weighted" in script and "predict" in script:
            # weighted-only seed-ish → still usually v1 path if policy present
            if "bloggo" in low or "ocr" in low:
                return "ocr_override"
        # Default mapkit-baseline re-run to current live ensemble (fail-loud).
        return "ensemble_v2"

    # Unnamed / other: only auto-refresh if the body is clearly our multi-module seed.
    if any(m in script for m in ("mapkit_vlm_live", "selector_list_fit", "mapkit_baseline_v2")):
        return "ensemble_v2"
    if any(m in script for m in ("mapkit_ocr_override", "poi_confidence_policy")):
        return "ocr_override"
    return None


def materialize_preset(preset: str) -> str:
    """Return current-repo script text for a refresh preset."""
    if preset == "ensemble_v2":
        return bundle_example_ensemble_v2()
    if preset == "ocr_override":
        return bundle_example_ocr_override()
    if preset == "nearest":
        path = _ROOT / "examples" / "baseline_nearest.py"
        return path.read_text(encoding="utf-8")
    raise ValueError(f"unknown refresh preset: {preset!r}")


def refresh_script_for_rerun(
    run_name: str,
    stored_script: str,
    *,
    force_preset: Optional[str] = None,
) -> Dict[str, Any]:
    """Pick current examples/bundle for Re-run, or keep the stored script.

    This closes the hole where Results → Re-run reloads a pre-fail-loud
    ``script_text`` snapshot and silently scores OCR-only under a live name.
    """
    stored = (stored_script or "").strip()
    preset = (force_preset or "").strip() or detect_refresh_preset(run_name, stored)
    if not preset:
        return {
            "refreshed": False,
            "preset": None,
            "script_text": stored,
            "message": "Using script_text stored on the prior run (no repo refresh mapping).",
        }
    text = materialize_preset(preset)
    compile(text, f"<refresh:{preset}>", "exec")
    return {
        "refreshed": True,
        "preset": preset,
        "script_text": text,
        "message": (
            f"Re-run script refreshed from current repo ({preset}). "
            "Prior-run script_text was not re-used, so fail-loud / live VLM "
            "policy matches this checkout."
        ),
        "stored_sha256": (
            __import__("hashlib").sha256(stored.encode("utf-8")).hexdigest()
            if stored
            else None
        ),
        "script_sha256": __import__("hashlib")
        .sha256(text.encode("utf-8"))
        .hexdigest(),
    }


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Bundle example modules into one predict() script")
    ap.add_argument(
        "preset",
        choices=("ensemble_v2", "ocr_override"),
        help="which curated multi-module algorithm to bundle",
    )
    ap.add_argument("-o", "--output", type=Path, help="write to file (default: stdout)")
    args = ap.parse_args(argv)

    text = (
        bundle_example_ensemble_v2()
        if args.preset == "ensemble_v2"
        else bundle_example_ocr_override()
    )
    compile(text, f"<bundle:{args.preset}>", "exec")
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
