#!/usr/bin/env python3
"""Bundle multi-module example algorithms into one self-contained script_text.

The eval harness only stores/runs a single ``script_text`` file. Sibling
modules under ``examples/`` are *not* put on PYTHONPATH (outside imports are
blocked). Use this bundler so seed baselines and multi-file algorithms become
one file that still re-exports ``predict``.

stdlib and installed third-party packages are left to normal import — only
repo-local source modules need inlining.
"""
from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent


def _read(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"missing module source: {path}")
    return path.read_text(encoding="utf-8")


def bundle_modules(
    modules: Sequence[Tuple[str, str]],
    *,
    entry: str,
    banner: Iterable[str] | None = None,
) -> str:
    """Return a self-contained Python source string.

    ``modules`` is an ordered list of ``(import_name, source_text)``. Earlier
    modules are installed first so later ones can ``import`` them. ``entry`` is
    the module name that must define ``predict``.
    """
    names = [n for n, _ in modules]
    if entry not in names:
        raise ValueError(f"entry module {entry!r} not in modules {names}")

    lines: List[str] = [
        "# Self-contained submission bundle.",
        "# Generated by tools/bundle_submission.py — edit sources under examples/.",
        "# Runtime may use the Python stdlib and installed site-packages only;",
        "# repo-local / sibling modules must be inlined here (not imported from disk).",
        "",
    ]
    if banner:
        for line in banner:
            lines.append("# " + line if line else "#")
        lines.append("")

    lines.extend(
        [
            "from __future__ import annotations",
            "",
            "import base64",
            "import sys",
            "import types",
            "",
            "def __poi_install_inline__(name: str, b64: str) -> None:",
            '    """Install one inlined module into sys.modules before entry runs."""',
            "    src = base64.b64decode(b64.encode('ascii')).decode('utf-8')",
            "    mod = types.ModuleType(name)",
            "    mod.__file__ = f'<submission-bundle>/{name}.py'",
            "    mod.__package__ = None",
            "    sys.modules[name] = mod",
            "    exec(compile(src, mod.__file__, 'exec'), mod.__dict__)",
            "",
        ]
    )

    for name, source in modules:
        b64 = base64.b64encode(source.encode("utf-8")).decode("ascii")
        lines.append(f"__poi_install_inline__({name!r}, (")
        chunk = 76
        for i in range(0, len(b64), chunk):
            lines.append(f"    {b64[i:i + chunk]!r}")
        lines.append("))")
        lines.append("")

    lines.extend(
        [
            f"_entry = sys.modules[{entry!r}]",
            "predict = _entry.predict",
            "if hasattr(_entry, 'DESCRIPTION'):",
            "    DESCRIPTION = _entry.DESCRIPTION",
            "if hasattr(_entry, 'RULE_VERSION'):",
            "    RULE_VERSION = _entry.RULE_VERSION",
            "if hasattr(_entry, 'decide'):",
            "    decide = _entry.decide",
            "",
        ]
    )
    return "\n".join(lines)


def bundle_paths(
    module_paths: Sequence[Tuple[str, Path]],
    *,
    entry: str,
    banner: Iterable[str] | None = None,
) -> str:
    modules = [(name, _read(path)) for name, path in module_paths]
    return bundle_modules(modules, entry=entry, banner=banner)


def bundle_example_ensemble_v2() -> str:
    ex = _ROOT / "examples"
    return bundle_paths(
        [
            ("mapkit_weighted", ex / "mapkit_weighted.py"),
            ("selector_list_fit", ex / "selector_list_fit.py"),
            ("selector_access_ocr", ex / "selector_access_ocr.py"),
            ("mapkit_vlm_live", ex / "mapkit_vlm_live.py"),
            ("mapkit_baseline_v2", ex / "mapkit_baseline_v2.py"),
        ],
        entry="mapkit_baseline_v2",
        banner=[
            "mapkit-baseline v2 — fully live ensemble (no curated residual list).",
            "list_fit@K20; on access≈nearest: live FastVLM skill@K5 (high-conf only).",
            "Write-through memo cache only (same key → same live result).",
            "Interpreter: POI_PREDICT_PYTHON or poi-data/tools/fastvlm-venv.",
            "POI_VLM_MODE=off → deterministic core only.",
        ],
    )


def bundle_example_ocr_override() -> str:
    ex = _ROOT / "examples"
    return bundle_paths(
        [
            ("mapkit_weighted", ex / "mapkit_weighted.py"),
            ("poi_confidence_policy", ex / "poi_confidence_policy.py"),
            ("mapkit_ocr_override", ex / "mapkit_ocr_override.py"),
        ],
        entry="mapkit_ocr_override",
        banner=[
            "mapkit-baseline v1 — Bloggo weighted + unique OCR name override.",
            "Self-contained bundle of mapkit_weighted + poi_confidence_policy + entry.",
        ],
    )


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Bundle example modules into one predict() script")
    ap.add_argument(
        "preset",
        choices=("ensemble_v2", "ocr_override"),
        help="which curated multi-module algorithm to bundle",
    )
    ap.add_argument("-o", "--output", type=Path, help="write to file (default: stdout)")
    args = ap.parse_args(argv)

    text = (
        bundle_example_ensemble_v2()
        if args.preset == "ensemble_v2"
        else bundle_example_ocr_override()
    )
    compile(text, f"<bundle:{args.preset}>", "exec")
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
